<?php

require_once('modele/posts.php');

if (isset($message)) {
	echo "<span style='color:green;'>".$message."</span>";
}

if (isset($_SESSION['user'])) {
	?>
	<a href='index.php?action=do_logout'>Déconnexion</a>
	<a href='index.php?action=new_post'>Ajouter post</a>
	<?php
}

else {
	?>
	<a href="index.php?action=signup">Inscription</a><a href="index.php?action=login">Connexion</a>
	<?php
}

?>
    <h1>Welcome !</h1>

    <div class="posts-container">
    <?php
    $posts = get_posts();

    foreach ($posts as $key => $value) {
    	$id_user = $value['idUser'];
		$user = get_author($value['idUser']);
		$post = '<div class="single">';
		$post .= '<h2>'.$value['title'].'</h2>';
		foreach ($user as $key2 => $value2) {
			$post .= '<i>Auteur : '.$value2['login'].'</i>';
		}
		$post .= '<div class="content">'.$value['content'].'</div>';
		if (isset($_SESSION['user']) && $id_user == $_SESSION['user']) {
			$post .= '<a href="index.php?action=new_post&post='.$value['idPost'].'">Modifier</a>';
			$post .= '<a href="index.php?action=delete_post&post='.$value['idPost'].'">Supprimer</a>';
		}
		$post .= '</div>';

		echo $post;
	}
    ?>
    </div>