<h1>Connexion</h1>

<?php

if (isset($errors)) {
  foreach ($errors as $key=>$error) {
    echo "<span style='color:red;'><b>erreur: </b>".$key.": ".$error."</span><br>";
  }
}

?>

<form action="index.php?action=do_login" method="post">
<div>login : <input type="text" name="login" <?php if(isset($_POST['login'])) { echo ('value="'.$_POST['login'].'"'); } ?>></div>
<div>pass : <input type="password" name="mdp"></div>
<input type="submit" value="Connexion">
</form>