<?php

require_once('modele/posts.php');

if (isset($errors))
{
  foreach ($errors as $key=>$error)
  {
    echo "<span style='color:red;'><b>erreur: </b>".$key.": ".$error."</span><br>";
  }
}

if (isset($_GET['post']))
{
	$post = get_post($_GET['post']);
	foreach ($post as $key => $value)
	{
		$title = $value['title'];
		$content = $value['content'];
	}
	$action = 'edit_post&post='.$_GET['post'];
	$submit = 'Modifier';
}
else
{
	$action = 'add_post';
	$submit = 'Ajouter';
}

?>

<h1>Créer un billet</h1>

<form action="index.php?action=<?php echo $action; ?>" method="post">
	<div>
		<label>Titre</label>
		<input type="text" name="title" <?php if(isset($_POST['title'])) { echo ('value="'.$_POST['title'].'"'); } elseif (!empty($post)) { echo ('value="'.$title.'"'); } ?>>
	</div>
	<div>
		<label>Contenu</label>
		<textarea name="content" class="content"><?php if(isset($_POST['content'])) { echo $_POST['content']; } elseif (!empty($post)) { echo $content; } ?></textarea>
	</div>
	<input type="submit" value="<?php echo $submit; ?>">
</form>