<?php

require_once('modele/posts.php');
require_once('modele/comments.php');
require_once('modele/user.php');

if (isset($errors)) {
  foreach ($errors as $key=>$error) {
    echo "<span style='color:red;'><b>erreur: </b>".$key.": ".$error."</span><br>";
  }
}

if (isset($_GET['comment'])) {
	$comment = get_comment($_GET['comment']);
	foreach ($comment as $key => $value) {
		$content = $value['content'];
	}
	$action = 'edit_comment&comment='.$_GET['comment'];
	$submit = 'Modifier';
}
else{
	$submit = 'Commenter';
}




?>

<h1>Modifier votre commentaire</h1>

<form action="index.php?action=edit_comment&comment=<?php echo $_GET['comment'] ?>&id=<?php echo $_GET['id'] ?>" method="post">
	<div>
		<label>Commentaire</label> 
		<textarea name="content" class="content"><?php if(isset($_POST['content'])) { echo $_POST['content']; } elseif (!empty($comment)) { echo $content; } ?></textarea>
	</div>
	<input type="submit" value="<?php echo $submit; ?>">
</form>