<?php

require_once('modele/billets.php');

if (isset($errors)) {
  foreach ($errors as $key=>$error) {
    echo "<span style='color:red;'><b>erreur: </b>".$key.": ".$error."</span><br>";
  }
}

if (isset($_GET['billet'])) {
	$billet = get_billet($_GET['billet']);
	foreach ($billet as $key => $value) {
		$title = $value['title'];
		$content = $value['content'];
	}
	$action = 'update_billet&billet='.$_GET['billet'];
	$submit = 'Modifier';
}
else{
	$action = 'add_billet';
	$submit = 'Ajouter';
}

?>

<h1>Créer un Billet</h1>

<form action="index.php?action=<?php echo $action; ?>" method="post">
<div>Titre : <input type="text" name="title" <?php if(isset($_POST['title'])) { echo ('value="'.$_POST['title'].'"'); } elseif (!empty($billet)) { echo ('value="'.$title.'"'); } ?>></div>
<div>Contenu : <textarea name="content" class="content" <?php if(isset($_POST['content'])) { echo ('value="'.$_POST['content'].'"'); } elseif (!empty($billet)) { echo ('value="'.$content.'"'); } ?>></textarea></div>
<input type="submit" value="<?php echo $submit; ?>">
</form>