<h1>Inscription</h1>

<?php

if (isset($errors)) {
  foreach ($errors as $key=>$error) {
    echo "<span style='color:red;'><b>erreur: </b>".$key.": ".$error."</span><br>";
  }
}

?>

<form action="index.php?action=do_signup" method="post">
<div>
	<label>Login</label>
	<input type="text" name="login" <?php if(isset($_POST['login'])) { echo ('value="'.$_POST['login'].'"'); } ?>></div>
<div>
	<label>Mot de passe</label>
	<input type="password" name="mdp"></div>
<div>
	<label>Confirmez le mot de passe</label>
	<input type="password" name="r_mdp"></div>
<div>
	<label>Email</label>
	<input type="email" name="mail" <?php if(isset($_POST['mail'])) { echo ('value="'.$_POST['mail'].'"'); } ?>></div>
	<input type="submit" value="Inscription">
</form>